services:
  web:
    build: ./web
    container_name: php_app
    ports:
      - "8000:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
    command: ["./wait-for-db.sh", "db", "5432", "apache2-foreground"]

  db:
    image: postgres:15
    container_name: pg_db
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"